# Generated by Django 3.0.7 on 2020-06-18 13:28

import academy.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('SEERAH', 'Seerah'), ('TAWHID', 'Tawhid'), ('HADITHS', 'Hadiths'), ('KHUTBA', 'Khutba'), ('FIQH', 'Fiqh'), ('TAFSIR', 'Tafsir'), ('BAYANE', 'Bayane')], max_length=10)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file_type', models.CharField(blank=True, choices=[('video', 'Video')], max_length=10)),
                ('upload', models.FileField(upload_to=academy.models.file_directory_path)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyPrivateQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyPublicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyPublicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.AcademyPublicQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='AcademyPrivateAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answer_date', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.AcademyPrivateQuestion')),
            ],
        ),
    ]
