# Generated by Django 3.0.7 on 2020-09-24 07:11

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyPrivateQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyPublicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.TextField()),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('videoUrl', embed_video.fields.EmbedVideoField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.YoutubePlaylist')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubePlaylistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SEERAH', 'Seerah'), ('TAWHID', 'Tawhid'), ('HADITHS', 'Hadiths'), ('KHUTBA', 'Khutba'), ('FIQH', 'Fiqh'), ('TAFSIR', 'Tafsir'), ('BAYANE', 'Bayane')], max_length=10)),
                ('playlistTitle', models.CharField(max_length=100)),
                ('playlistUrl', embed_video.fields.EmbedVideoField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.YoutubePlaylist')),
            ],
        ),
        migrations.CreateModel(
            name='AcademyPublicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answerDate', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.AcademyPublicQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='AcademyPrivateAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answerDate', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.AcademyPrivateQuestion')),
            ],
        ),
    ]
