# Generated by Django 3.0.7 on 2020-12-17 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyPrivateQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('sexe', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('N', 'Neutral')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='AcademyPublicQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('questionText', models.TextField()),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubePlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('videoUrl', embed_video.fields.EmbedVideoField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.YoutubePlaylist')),
            ],
        ),
        migrations.CreateModel(
            name='YoutubePlaylistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('SEERAH', 'Seerah'), ('TAWHID', 'Tawhid'), ('HADITHS', 'Hadiths'), ('KHUTBA', 'Khutba'), ('FIQH', 'Fiqh'), ('TAFSIR', 'Tafsir'), ('BAYANE', 'Bayane')], max_length=10)),
                ('playlistUrl', embed_video.fields.EmbedVideoField(blank=True, default=None)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.YoutubePlaylist')),
            ],
        ),
        migrations.CreateModel(
            name='SupportSingle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='item/')),
                ('supports_dir', models.FileField(null=True, upload_to='supports/', verbose_name='Supports')),
                ('name_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.SupportCollection')),
            ],
        ),
        migrations.CreateModel(
            name='AcademyPublicAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answerDate', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.AcademyPublicQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='AcademyPrivateAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answerDate', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.AcademyPrivateQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='AcademyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(default=None)),
                ('price', models.DecimalField(decimal_places=6, max_digits=10)),
                ('category', models.CharField(choices=[('SEERAH', 'Seerah'), ('TAWHID', 'Tawhid'), ('HADITHS', 'Hadiths'), ('KHUTBA', 'Khutba'), ('FIQH', 'Fiqh'), ('TAFSIR', 'Tafsir'), ('BAYANE', 'Bayane')], max_length=10)),
                ('thumbnail', models.ImageField(null=True, upload_to='thumbnails/')),
                ('videos_dirs', models.FileField(null=True, upload_to='videos/', verbose_name='Videos')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('supports_dirs', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='academy.SupportCollection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
