# Generated by Django 3.0.7 on 2020-12-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20201217_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='items',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='items',
            field=models.ManyToManyField(related_name='items', to='academy.AcademyModel'),
        ),
    ]
