# Generated by Django 3.0.7 on 2020-12-18 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20201217_2256'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
